### ISSUE TITLE
ActionSequence has constant size

### ISSUE THREAD

**Issue by martinei** [jlink/jqwik#196] opened 2021-06-16 08:13 UTC
## Testing Problem
My ActionSequence always has a fixed size of 32:

```java
@Property
    void check(@ForAll("actions")  ActionSequence<String> actions) {
        Statistics.collect(actions.size());
        actions.run("");
    }
    @Provide
    public Arbitrary<ActionSequence<String>> actions() {
        var action = new  Action<String>() {
            @Override
            public String run(String state) {
                return state; // NoOp
            }
        };
        var result =  Arbitraries.sequences(
                Arbitraries.of(action));
        return result;
    }
```
    
    results in:
    
 ```
 statistics = 
    32 (1000) : 100 %    
 ```
 Am I Missing something? I expected it to be varying between 1 and 32 from what I read in the docu.

**Comment by jlink** [comment] 2021-06-16 09:37
It works as designed :-/

At some point I stopped to vary the size of sequences because cutting a sequence shorter than it could be does not provide additional value. At least that was my train of thought.

If you can point to the part of the documentation that lead you to believe otherwise, I will change it.

**Comment by jlink** [comment] 2021-06-16 09:44
I found the place: 
"For the default of 1000 tries a sequence will have up to 32 actions."

I'm gonna tell the readers the truth from now on.

**Comment by jlink** [comment] 2021-06-16 10:03
Fixed in https://github.com/jlink/jqwik/commit/9a5b05f7c3d6b60de18ed85454003c88740e462c

**Closed by jlink** 2021-06-16 10:03 UTC
Labels: documentation

**Comment by martinei** [comment] 2021-06-16 10:05
Thanks!
