### ISSUE TITLE
Edge case configuration not working in either 1.4.0 or 1.5.0

### ISSUE THREAD

**Issue by galderz** [jlink/jqwik#171] opened 2021-02-25 10:27 UTC
Edge case configuration seems broken in both 1.4.0 and 1.5.0.

With `1.3.10` the edge case configuration would work:

```
System.out.println(
    Arbitraries.doubles().edgeCases(cfg -> cfg.add(Double.MIN_VALUE))
        .edgeCases().suppliers().stream().map(Supplier::get).map(Shrinkable::value)
        .collect(Collectors.toList())
);

// Prints:
// [0.0, 1.0, -1.0, 0.01, -0.01, -1.7976931348623157E308, 1.7976931348623157E308, 4.9E-324]
```

In `1.4.0`, the `MIN_VALUE` is not there, and in the latest `1.5.0` the `MIN_VALUE` seems replaced by `0.0`:

```
System.out.println(
    Arbitraries.doubles().edgeCases(cfg -> cfg.add(Double.MIN_VALUE))
        .edgeCases().suppliers().stream().map(Supplier::get).map(Shrinkable::value)
        .collect(Collectors.toList())
);

// Prints:
// [0.0, 1.0, -1.0, 0.01, -0.01, -1.7976931348623157E308, 1.7976931348623157E308, 0.0]
```

**Comment by jlink** [comment] 2021-02-25 13:57
High @galderz.

As discussed in https://github.com/jlink/jqwik/issues/163 all edge cases undergo the arbitraries "precision" which is determined by `ofScale(..)`. Moreover, starting with 1.4.0 number-based arbitraries check if added edge cases are within the allowed range. So what you see is behaviour "as designed", except I will see if adding edge cases outside the spec could show a decent error message or at least a warning.

As for your need to include MIN_VALUE and NaN and alike I'd do the following:

```java
Arbitrary<Double> doublesWithAdditionalEdgeCases = Arbitraries.frequencyOf(
		Tuple.of(20, Arbitraries.doubles()),
		Tuple.of(1, Arbitraries.of(Double.MIN_VALUE, Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY))
);

doublesWithAdditionalEdgeCases.sampleStream().limit(100).forEach(System.out::println);
```

This will generate one of the additional "edge cases" with a frequency of 1 in 21.

Does that help?

**Comment by jlink** [comment] 2021-02-26 10:55
Closing as wont fix. Feel free to reopen if some questions remain open.

**Closed by jlink** 2021-02-26 10:55 UTC
Labels: wontfix

**Comment by galderz** [comment] 2021-03-01 07:12
> Does that help?

No, not really. In my case I want a sample of say 1000 doubles, and then all the edge cases to be covered. I don't think your suggestion does that.

**Comment by jlink** [comment] 2021-03-01 07:26
It should with a high probability, have you tried? Edge case injection is also randomized i.e. depending on the number of edge cases and number of tries you cannot be 100% _sure_ that all are covered, unless you use `@Property(edgeCases=FIRST)` which I do not really recommend because with a high number of (combinatorial) edge cases you might not have any randomized input.

If you want to make 100% sure that some data is being tried, you can go with data-driven properties: https://jqwik.net/docs/current/user-guide.html#data-driven-properties
Usually in addition to randomized properties.

**Comment by galderz** [comment] 2021-03-09 07:44
I tried and created a unit test but doesn't always work. Seems way over the top to have to use data-driven properties when all you really want is to enhance an existing arbitrary to guarantee that a certain value will be tested. Is it really that hard? :\

**Comment by jlink** [comment] 2021-03-10 11:30
How many additional edge cases do you have?

**Comment by galderz** [comment] 2021-03-12 11:19
```
Double.NaN
, Double.NEGATIVE_INFINITY
, Double.MIN_VALUE
, -Double.MIN_VALUE
, Double.MIN_NORMAL
, -Double.MIN_NORMAL
, Double.POSITIVE_INFINITY
```

**Comment by galderz** [comment] 2021-03-12 11:20
The funny thing is that `Double.MAX_VALUE` and `-Double.MAX_VALUE` are already included.

**Comment by galderz** [comment] 2021-03-12 11:30
Why can these values important for me? Because one could naively thing that this is valid:

```
    @Property
    void test000(@ForAll double a, @ForAll double b)
    {
        assertThat(
            Double.compare(a, b) < 1
            , is(a <= b)
        );
    }
```

However, add `Double.NaN` to the picture and it breaks.

**Comment by jlink** [comment] 2021-03-12 15:34
I tried another idea:

```java
static final Double[] specials = {
		Double.NaN
		, Double.NEGATIVE_INFINITY
		, Double.MIN_VALUE
		, -Double.MIN_VALUE
		, Double.MIN_NORMAL
		, -Double.MIN_NORMAL
		, Double.POSITIVE_INFINITY
};

@Provide
Arbitrary<Double> withSpecials() {
	Arbitrary<Double> specialsArbitrary = Arbitraries.of(specials).edgeCases(c -> c.add(specials));
	return Arbitraries.frequencyOf(
			Tuple.of(20, Arbitraries.doubles()),
			Tuple.of(1, specialsArbitrary)
	);
}
```

Since now all _specials_ are also edge cases they are being generated more frequently and you can influence them through `@Property(edgeCases = EdgeCasesMode.FIRST|MIXIN|NEVER)`.  

The following statistics check never failed once in > 5000 tries:

```java
@Property(afterFailure = AfterFailureMode.RANDOM_SEED)
void statistics(@ForAll("withSpecials") double a) {
	if (Arrays.asList(specials).contains(a)) {
		Statistics.collect(a);
	} else {
		Statistics.collect("not special");
	}
	Statistics.coverage(checker -> {
		for (Double special : specials) {
			checker.check(special).count(c -> c > 0);
		}
	});
}
```

Arguable there could be a shortcut for `Arbitraries.of(values).edgeCases(c -> c.add(values))`.  E.g. `Arbitraries.ofEdgeCases(values)`. 
I'm happy about such a feature request.

**Comment by jlink** [comment] 2021-03-30 08:03
@galderz Would something like `DoubleArbitrary.injectNaN() | injectNegativeInfinity() | injectPositiveInfinity() | injectMinNormal() | injectMinValue()` be helpful?

I'm just planning upcoming releases and might schedule it iff there is enough interest.

**Comment by galderz** [comment] 2021-04-19 12:53
@jlink I'm working on other stuff right now, so I've not been able to try out your last idea. I'll provide feedback on that when I get back to it.

**Comment by jlink** [comment] 2021-08-08 09:53
@galderz The feature you triggered is now part of jqwik (release 1.5.4-SNAPSHOT). 

Here's the documentation: https://jqwik.net/docs/snapshot/user-guide.html#special-decimal-values

Would love to hear your feedback!

**Comment by galderz** [comment] 2021-08-19 09:52
Nice!!! Thanks a lot for that :)
