### ISSUE TITLE
Do not depend on junit-platform-engine for the API

### ISSUE THREAD

**Issue by piefel** [jlink/jqwik#31] opened 2018-07-26 09:55 UTC
jqwik comes with a dependency on junit-platform-engine:

    compile("org.junit.platform:junit-platform-engine:${junitPlatformVersion}")

A little surprsingly, this may cause trouble. I have a Maven project that also uses JUnit Jupiter tests and only has the dependency on `junit-jupiter-engine` in the Surefire configuration (Jupiter, in contrast to jqwik, comes with two dependencies, one for the API and one for the engine).

When running tests through IntelliJ in this project with 3 engines, often IntelliJ cannot find the tests. The details are not too important (issue raised with JetBrains), but the solution is to _exclude_ the dependency on the platform engine in the POM.

My request here is to split jqwik into API and engine as Jupiter does. Alternatively, exluding junit-platform-engine from the exported dependencies may help, and a note in the docs to include it for the few users that use jqwik exclusively and thus do not get the dependency in any other way.

**Comment by jlink** [comment] 2018-07-26 10:00
Thanks for pointing that out. I'll have a look at it...

**Comment by jlink** [comment] 2018-07-26 13:00
If I understand you correctly, it's basically an IntelliJ bug - maybe you can paste in the youtrack ID from youtrack.jetbrains.com so that I can follow the progress.

Creating two artefacts would be 
1) quite a big change to the way I currently do releases
2) an additional burden for those users that don't run into your problem

Your second suggestion does also not feel right, because it would lie about the real dependency.

I'm not a maven expert, so here's my question: Does Maven provide a way to exclude transparent dependencies (I loosely remember an <exclusions> tag)? Gradle also has such a mechanism, and I could document the steps to work around this IntelliJ issue until it will be resolved.

What do you think?

**Comment by piefel** [comment] 2018-07-27 07:58
It is an IntelliJ problem, that’s correct. There is no YouTrack ticket, only my support ticket which is not public. I don’t see why test discovery should be affected by things on the classpath, but there it is. The IntelliJ test support may depend too much on the structure that JUnit 5 uses itself (separated API and engine).

I don’t know what transparent dependencies are, but assuming you mean transitive, then of course, they can be excluded, and that is in fact what I’m doing:

        <dependency>
            <groupId>net.jqwik</groupId>
            <artifactId>jqwik</artifactId>
            <version>${jqwik.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.platform</groupId>
                    <artifactId>junit-platform-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

About the ‘lying’ part: I’m not sure it is lying. Nothing in the jqwik _library_ depends on the platform engine. To actually _run_ the tests it is needed, but that is a dependency of the test runtime. You wouldn’t normally include the EL dependency in a WAR when you know it’s going to run in a Tomcat.

Feel free _not_ to fix the dependency, but perhaps leave open this ticket for reference if other people stumble upon the same issue.

**Comment by jlink** [comment] 2018-07-27 09:00
"transparent" should be "transitive" of course :-)

Leaving the issue open for the time being sounds like a good suggestion. I will add the related Gradle code in another comment.

**Comment by jlink** [comment] 2018-07-27 09:05
@piefel Can you point to an example where I can see the IntelliJ bug or the issue tracker ID for it? I could not reproduce your problem in my experiments.

**Comment by piefel** [comment] 2018-07-30 11:05
I can create a small Git repo and share the link.

**Comment by jlink** [comment] 2018-12-19 19:49
Has hopefully been resolved with https://github.com/jlink/jqwik/issues/37

**Closed by jlink** 2018-12-19 19:49 UTC
