### ISSUE TITLE
DefaultSetArbitrary#flatMapEach should use LinkedHashMap instead of HashMap for reproducible results

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#340] opened 2022-05-22 16:35 UTC
## Testing Problem

`HashSet` might cause non-reproducible results even if the same `seed` is provided.
For instance, `HashMap` might use `identityHashCode` as a tie-breaker

`Collectors.toSet()` seems to be impacted as well.

## Suggested Solution

Use `LinkedHashSet` for `DefaultSetArbitrary#flatMapEach`

**Comment by jlink** [comment] 2022-05-26 16:21
@vlsi Thanks for digging into that. I didn’t know about the tie-breaking mechanisms in HashSet. Getting rid of it looks like a possibility. 

I’ll have a closer look at it (and all the other issues you‘ve opened recently) when I get out of my current time hole, hopefully in a week or so.

**Comment by jlink** [comment] 2022-06-19 09:38
I think the test for reproducing the problem should use two freshly created generators:

```java
@Property
void setGenerationHasConsistentOrderForSameRandomSeed(@ForAll Random random, @ForAll @IntRange(min = 1, max = 20) int size) {
	Arbitrary<Integer> integerArbitrary = Arbitraries.integers().between(1, 1000);
	Arbitrary<Set<Object>> values = integerArbitrary.<Object>map(x -> new Object() {
		@Override
		public String toString() {
			return String.valueOf(x);
		}
	}).set().mapEach((set, value) -> value);
	RandomGenerator<Set<Object>> gen1 = values.generator(1000, true);
	RandomGenerator<Set<Object>> gen2 = values.generator(1000, true);
	for (int i = 0; i < size; i++) {
		long seed = random.nextLong();
		assertThat(gen1.next(SourceOfRandomness.newRandom(seed)).value())
			.isEqualTo(gen2.next(SourceOfRandomness.newRandom(seed)).value());
	}
}
```

Luckily it also fails :-)

**Comment by jlink** [comment] 2022-07-02 11:01
Hopefully fixed with https://github.com/jlink/jqwik/commit/3840a4ba76a56d08814d97f705d0e11b5fbc50d1

**Closed by jlink** 2022-07-02 11:01 UTC
