### ISSUE TITLE
Running single parameterized property in IDEA fails to find the property (test)

### ISSUE THREAD

**Issue by brianm** [jlink/jqwik#12] opened 2018-04-07 22:17 UTC
## Testing Problem

Running individual jqwik test fails in IDEA with the error:

```java
2018-04-07 22:11:41 WARNING TestEngine with ID 'jqwik' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to load parameter type [[byte] for method [testFoo] in class [com.example.SomeTest].
	at org.junit.platform.commons.util.ReflectionUtils.lambda$loadRequiredParameterType$13(ReflectionUtils.java:832)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.commons.util.ReflectionUtils.loadRequiredParameterType(ReflectionUtils.java:831)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$resolveParameterTypes$11(ReflectionUtils.java:825)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.junit.platform.commons.util.ReflectionUtils.resolveParameterTypes(ReflectionUtils.java:826)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:815)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:169)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:142)
	at net.jqwik.discovery.JqwikDiscoverer.lambda$discover$4(JqwikDiscoverer.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.jqwik.discovery.JqwikDiscoverer.discover(JqwikDiscoverer.java:48)
	at net.jqwik.JqwikTestEngine.discover(JqwikTestEngine.java:33)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:48)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

2018-04-07 22:11:41 WARNING TestEngine with ID 'jqwik' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to load parameter type [[byte] for method [testFoo] in class [com.groupon.ezsc.KeyCiphertextTest].
	at org.junit.platform.commons.util.ReflectionUtils.lambda$loadRequiredParameterType$13(ReflectionUtils.java:832)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.commons.util.ReflectionUtils.loadRequiredParameterType(ReflectionUtils.java:831)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$resolveParameterTypes$11(ReflectionUtils.java:825)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.junit.platform.commons.util.ReflectionUtils.resolveParameterTypes(ReflectionUtils.java:826)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:815)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:169)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:142)
	at net.jqwik.discovery.JqwikDiscoverer.lambda$discover$4(JqwikDiscoverer.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.jqwik.discovery.JqwikDiscoverer.discover(JqwikDiscoverer.java:48)
	at net.jqwik.JqwikTestEngine.discover(JqwikTestEngine.java:33)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 0
Empty test suite.
```

This occurs for any parameterized test annotated with `@Property` when you attempt to run a single test. Running an entire test class works fine. Running `@Example` non-parameterized tests works fine.

## Suggested Solution

Fix the test runner?

## Discussion

It is useful to be able to narrow in on a single test in a class.

**Comment by brianm** [comment] 2018-04-07 22:33
Debugging into this, it looks like the discovery request for (byte[], byte[]) param types comes in as `[byte,[byte` which explodicates. I cannot find docs for the protocol for passing in method param type descriptors, and the [javadocs on MethodSelector](https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/MethodSelector.html#getMethodParameterTypes--) are... not awesome.

**Comment by brianm** [comment] 2018-04-07 22:46
Confirmed, it happens on arrays but not single objects.

**Comment by jlink** [comment] 2018-04-08 09:33
Checked it. Here's what I found...

## Overview

The problem seems to occur only with primitive array types. And it does not occure withing the jqwik part of the execution chain. Which sounds like a good thing for me - because I don't have to fix it - but it's also a bad thing for me - because I CANNOT fix it :-(

## Details

The selector (an instance of class `MethodSelector`) that jqwik gets from the framework (aka JUnit Platform) is wrong. Wrong in the sense
that there's a method parameter type encoded as "[byte" which should be encoded as "[B". So the problem lies either in IntelliJ code or in some JUnit 5 platform support code. I'd bet on the former if I had to.

## What you can do

If you care enough for the problem to be fixed, you should do the following:
- Reproduce the bug with a parameterized Jupiter test. Why? Because Jupiter (aka JUnit 5) is much more common than jqwik and will attract more attention.
- Open an issue for both [junit5](https://github.com/junit-team/junit5) and [IntelliJ](https://youtrack.jetbrains.com/)
- Add the links to the issues here, so that I can also track any advances in this topic.
- Hope that the JUnit team and the IntelliJ team will sort out the underlying problem.

I'm sorry that I can't offer a better solution.

## One more thing

It's helpful for any issue you create to provide at least
1. A code example or even a failing test
2. The version numbers of all participating parties, in this case of jqwik, the junit platform and IntelliJ

**Comment by sormuras** [comment] 2018-04-09 09:27
![image](https://user-images.githubusercontent.com/2319838/38490179-ae5e9784-3be8-11e8-9b6a-a08ac8fe90e9.png)

Looks like a bug in IDEA. The IDE should feed `[B` as the parameter type, @akozlova -- am I right?

**Comment by akozlova** [comment] 2018-04-09 10:37
Please see https://github.com/junit-team/junit5/issues/815. IDEA never passes VM names, only source names.

**Comment by sormuras** [comment] 2018-04-09 11:12
I remember that one. Wasn't the solution to send `byte[]` instead of a mesh-up like `[byte`?

**Comment by akozlova** [comment] 2018-04-09 11:32
I don't remember exactly, but `[Ljava.lang.String;` is similar to `[byte` to me.

**Comment by sormuras** [comment] 2018-04-09 11:34
We should take the discussion over to https://github.com/junit-team/junit5/issues/815

@brianm a possible work-around is to use `java.nio.ByteBuffer` for now. Replace `byte[] data` with `ByteBuffer data` in your test method and wrap the bytes with `ByteBuffer.wrap(...)`.

**Comment by sbrannen** [comment] 2018-04-09 12:06
This is a bug in IntelliJ.

The supported syntax is clearly documented here:

https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod-java.lang.String-

**Comment by sbrannen** [comment] 2018-04-09 12:07
`[byte` is neither valid in source code nor in binary.

**Comment by sbrannen** [comment] 2018-04-09 12:36
@brianm,

> I cannot find docs for the protocol for passing in method param type descriptors, and the javadocs on MethodSelector are... not awesome.

Good point.

I introduced cross referencing in [this commit](https://github.com/junit-team/junit5/commit/d9ae3286d7c59fd4129c8bd29aaf0601aa3d3667).

**Comment by akozlova** [comment] 2018-04-09 12:45
This will teach me again to do nothing before I actually can check it. I had a test data for [int array which I thought would be supported. Here is the IDEA issue: https://youtrack.jetbrains.com/issue/IDEA-189846

**Comment by sbrannen** [comment] 2018-04-09 12:55
@akozlova, no worries... We are all quite confident that you will fix it blazingly fast (as always)! 😉

**Comment by jlink** [comment] 2018-05-26 15:13
@akozlova Any news on this front?

**Comment by akozlova** [comment] 2018-05-28 08:29
I've created issue in IDEA's tracker (IDEA-189846) and resolved it in the same day. I am not aware of anything else I should do here.

**Comment by jlink** [comment] 2018-05-29 14:56
Has been fixed in in IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-189846

Available probably in version 2018.2

**Comment by jlink** [comment] 2018-05-29 14:56
@akozlova Thanks, the fix somehow slipped my mind.

**Closed by jlink** 2018-05-29 14:56 UTC

**Comment by jlink** [comment] 2018-08-01 07:00
The fix is included in IntelliJ 2018.2. Everything works as expected :-)

**Comment by nick318** [comment] 2020-06-15 13:42
@jlink seems the issue reproduces again using jqwik 1.3.0 and IDEA 2020.1

**Comment by jlink** [comment] 2020-06-15 14:12
I cannot reproduce with 

```
@Property
void test(@ForAll byte[] bytes) {}
```

@nick318 Can you be more specific about the failure you are observing?
